name: Run Tests

on:
  push:
    paths:
      - 'layered_model.py'
      - 'layered_model_test.py'
  pull_request:
    paths:
      - 'layered_model.py'
      - 'layered_model_test.py'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow pytest

    - name: Run tests
      run: |
        pytest layered_model_test.py
